// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOx-GpMnTr_6Cwrt_v-HVVxngw8ypLdec',
    appId: '1:25042210696:web:c5aad902ce8a6bf975f43d',
    messagingSenderId: '25042210696',
    projectId: 'fashion-outlet-75236',
    authDomain: 'fashion-outlet-75236.firebaseapp.com',
    storageBucket: 'fashion-outlet-75236.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7pf-Qdf8gIXgA4TzpNtKLFhz73taX218',
    appId: '1:25042210696:android:081be1dba972c29b75f43d',
    messagingSenderId: '25042210696',
    projectId: 'fashion-outlet-75236',
    storageBucket: 'fashion-outlet-75236.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVhTlTq4VFyQ1bAO5iK4xQ9zeu1zbKGxE',
    appId: '1:25042210696:ios:bce7ac10262cfb3975f43d',
    messagingSenderId: '25042210696',
    projectId: 'fashion-outlet-75236',
    storageBucket: 'fashion-outlet-75236.firebasestorage.app',
    iosBundleId: 'com.example.nhom10UngDungBanDoThoiTrangOutlet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVhTlTq4VFyQ1bAO5iK4xQ9zeu1zbKGxE',
    appId: '1:25042210696:ios:bce7ac10262cfb3975f43d',
    messagingSenderId: '25042210696',
    projectId: 'fashion-outlet-75236',
    storageBucket: 'fashion-outlet-75236.firebasestorage.app',
    iosBundleId: 'com.example.nhom10UngDungBanDoThoiTrangOutlet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOx-GpMnTr_6Cwrt_v-HVVxngw8ypLdec',
    appId: '1:25042210696:web:e86df2024a87815b75f43d',
    messagingSenderId: '25042210696',
    projectId: 'fashion-outlet-75236',
    authDomain: 'fashion-outlet-75236.firebaseapp.com',
    storageBucket: 'fashion-outlet-75236.firebasestorage.app',
  );
}
